/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rad.demo.ui.admins;

import com.rad.demo.database.AdminsSQL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author BHARATHA
 */
public class ChangePWView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ChangePW
     */
    private int adminId;

    public ChangePWView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCPW = new javax.swing.JLabel();
        lblCnPW = new javax.swing.JLabel();
        lblNPW = new javax.swing.JLabel();
        txtCPW = new javax.swing.JPasswordField();
        txtNPW = new javax.swing.JPasswordField();
        txtCnPW = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Change Password");

        lblMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(153, 0, 0));
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText("Message");

        lblCPW.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPW.setText("Current password :");

        lblCnPW.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCnPW.setText("Confirm Password :");

        lblNPW.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNPW.setText("New Password      :");

        txtCPW.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPWFocusGained(evt);
            }
        });

        txtNPW.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNPWFocusGained(evt);
            }
        });

        txtCnPW.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCnPWFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCnPW)
                        .addGap(18, 18, 18)
                        .addComponent(txtCnPW))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNPW)
                        .addGap(18, 18, 18)
                        .addComponent(txtNPW, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCPW)
                        .addGap(18, 18, 18)
                        .addComponent(txtCPW)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNPW, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(lblNPW))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCnPW, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCnPW))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPW)
                    .addComponent(txtCPW, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMessage)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String current = txtCPW.getText();
        String newPw = txtNPW.getText();
        String confirm = txtCnPW.getText();
        String password = null;
        try {
            password = AdminsSQL.getPassword(adminId);
        } catch (SQLException ex) {
            Logger.getLogger(ChangePWView.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (newPw.equals("")) {
            lblMessage.setText("Please enter new password!");
        } else if (confirm.equals("")) {
            lblMessage.setText("Please confirm your password!");
        } else if (current.equals("")) {
            lblMessage.setText("Please enter your current password!");
        } else {
            if (confirm.equals(newPw)) {
                if (current.equals(password)) {
                    AdminsSQL.setPassword(confirm, adminId);
                    JOptionPane.showMessageDialog(this, "Password changed successfully!", "", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } else {
                    lblMessage.setText("Invalid current password!");
                    txtCPW.setText("");
                }
            } else {
                lblMessage.setText("Your new Password does not match!");
                txtCnPW.setText("");
                txtCPW.setText("");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNPWFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNPWFocusGained
        lblMessage.setText("");
    }//GEN-LAST:event_txtNPWFocusGained

    private void txtCnPWFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCnPWFocusGained
        lblMessage.setText("");
    }//GEN-LAST:event_txtCnPWFocusGained

    private void txtCPWFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPWFocusGained
        lblMessage.setText("");
    }//GEN-LAST:event_txtCPWFocusGained

    public void initializeView(int adminId) {
        this.adminId = adminId;
        lblMessage.setText("");
        txtCPW.setText("");
        txtNPW.setText("");
        txtCnPW.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCPW;
    private javax.swing.JLabel lblCnPW;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNPW;
    private javax.swing.JPasswordField txtCPW;
    private javax.swing.JPasswordField txtCnPW;
    private javax.swing.JPasswordField txtNPW;
    // End of variables declaration//GEN-END:variables
}
