/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rad.demo.ui.admins;

import com.rad.demo.database.AdminsSQL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Gayani
 */
public class NewAdminView extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewAdmin
     */
    public NewAdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpRole = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblRole1 = new javax.swing.JLabel();
        lblNic1 = new javax.swing.JLabel();
        lblPhone1 = new javax.swing.JLabel();
        lblMail1 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtNic = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        btnAdmin = new javax.swing.JRadioButton();
        btnHead = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setClosable(true);

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitle1.setText("Title      :");

        lblName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName1.setText("Name   :");

        lblRole1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRole1.setText("Role      :");

        lblNic1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNic1.setText("NIC       :");

        lblPhone1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhone1.setText("Phone   :");

        lblMail1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMail1.setText("E-mail   :");

        txtTitle.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtNic.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtMail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        grpRole.add(btnAdmin);
        btnAdmin.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAdmin.setSelected(true);
        btnAdmin.setText("Admin");

        grpRole.add(btnHead);
        btnHead.setText("Head");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName1)
                                    .addComponent(lblTitle1))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRole1)
                                    .addComponent(lblNic1))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addComponent(txtNic)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdmin)
                                .addGap(18, 18, 18)
                                .addComponent(btnHead))
                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPhone1)
                                    .addComponent(lblMail1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMail)
                                    .addComponent(txtPhone))))))
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle1)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtName)
                        .addGap(2, 2, 2))
                    .addComponent(lblName1))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole1)
                    .addComponent(btnAdmin)
                    .addComponent(btnHead))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNic1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhone1)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(lblMail1))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addNewAdmin(String title, String name, String role, String nic, String phone, String mail, int maxId) {
        String last_logged = "0000-00-00 00:00:00";
        int admin_id = maxId + 1;
        String g = String.valueOf(admin_id);
        int l = g.length();
        String un = null;
        switch (l) {
            case 1:
                un = "000" + g;
                break;
            case 2:
                un = "00" + g;
                break;
            case 3:
                un = "0" + g;
                break;
            case 4:
                un = g;
                break;
            default:
                JOptionPane.showMessageDialog(this, "Sorry, Maximum number of admins is reached!", "Warning", JOptionPane.WARNING_MESSAGE);
                this.dispose();
                break;
        }
        String uname = "lab" + un;
        String password = role.toLowerCase();

        AdminsSQL.addNewAdmin(0, title, name, role, nic, phone, mail, uname, password, last_logged, 0, 1);
        JOptionPane.showMessageDialog(this, role + " was added successfully.\n\nUser Name : " + uname + "\nPassword : " + password + "\n", "", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int maxid = 0;
        try {
            maxid = AdminsSQL.getMaxId();
        } catch (SQLException ex) {
            Logger.getLogger(NewAdminView.class.getName()).log(Level.SEVERE, null, ex);
        }

        btnAdmin.setActionCommand("Admin");
        btnHead.setActionCommand("Head");

        String title1 = txtTitle.getText();
        String name = txtName.getText();
        String role = grpRole.getSelection().getActionCommand();
        String nic = txtNic.getText();
        String phone = txtPhone.getText();
        String mail = txtMail.getText();

        int id = 0;
        String input = null;
        try {
            id = AdminsSQL.getIdByName(name);
        } catch (SQLException ex) {
            Logger.getLogger(EditProfileView.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (title1.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a title!", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (name.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a name!", "", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (txtNic.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter NIC number");
            return;
        }
        Pattern nicp = Pattern.compile("(\\d{9}[V])*");
        Matcher m = nicp.matcher(txtNic.getText());
        if (!m.matches()) {
            JOptionPane.showMessageDialog(this, "Enter valid NIC number");
            return;
        }

        if (txtPhone.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter contact number");
            return;
        }
        Pattern pp = Pattern.compile("(\\d{10})*");
        m = pp.matcher(txtPhone.getText());
        if (!m.matches()) {
            JOptionPane.showMessageDialog(this, "Enter valid contact number");
            return;
        }

        if (txtMail.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter E-mail");
            return;
        }
        Pattern ep = Pattern.compile("(^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$)*", Pattern.CASE_INSENSITIVE);
        m = ep.matcher(txtMail.getText());
        if (!m.matches()) {
            JOptionPane.showMessageDialog(this, "Enter valid E-mail");
            return;
        }

        if (id == 0) {
            addNewAdmin(title1, name, role, nic, phone, mail, maxid);
        } else {
            JOptionPane.showMessageDialog(this, "This name already exists!", "Warning", JOptionPane.WARNING_MESSAGE);
            txtName.setText("");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    void initializeView() {
        txtTitle.setText("");
        txtName.setText("");
        txtNic.setText("");
        txtPhone.setText("");
        txtMail.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JRadioButton btnAdmin;
    private javax.swing.JRadioButton btnHead;
    private javax.swing.ButtonGroup grpRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMail1;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblNic1;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblRole1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables

}
