/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rad.demo.ui.admins;

import com.rad.demo.database.AdminsSQL;
import com.rad.demo.entities.Admins;
import com.rad.demo.ui.DashBoardView;
import static com.rad.demo.ui.DashBoardView.DesktopPane;
import java.awt.Component;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author BHARATHA
 */
public class SingleAdminView extends javax.swing.JInternalFrame {

    private int adminId;
    private int id;

    // private final AdminDetailsView adnewView = new AdminDetailsView();
    /**
     * Creates new form SingleAdminView
     */
    public SingleAdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblRole1 = new javax.swing.JLabel();
        lblNic1 = new javax.swing.JLabel();
        lblPhone1 = new javax.swing.JLabel();
        lblMail1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblNic = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Details");

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitle1.setText("Title      :");

        lblName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName1.setText("Name   :");

        lblRole1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRole1.setText("Role      :");

        lblNic1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNic1.setText("NIC       :");

        lblPhone1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhone1.setText("Phone   :");

        lblMail1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMail1.setText("E-mail   :");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitle.setText("Title");

        lblRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRole.setText("Role");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName.setText("Name");

        lblNic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNic.setText("NIC");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhone.setText("Phone");

        lblMail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMail.setText("E-mail");

        jButton1.setText("Change Role");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRole1)
                            .addComponent(lblNic1)
                            .addComponent(lblName1)
                            .addComponent(lblTitle1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhone1)
                            .addComponent(lblMail1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle1)
                    .addComponent(lblTitle))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName1)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole1)
                    .addComponent(lblRole))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNic1)
                    .addComponent(lblNic))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone1)
                    .addComponent(lblPhone))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMail1)
                    .addComponent(lblMail))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int input = JOptionPane.showConfirmDialog(this, "Do you want to change the role?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (input == JOptionPane.YES_OPTION) {
            try {
                pfAction();
            } catch (SQLException ex) {
                Logger.getLogger(SingleAdminView.class.getName()).log(Level.SEVERE, null, ex);
            }

            this.dispose();
            DashBoardView.DesktopPane.remove((Component) this);
            DashBoardView.DesktopPane.add((Component) this);
            try {
                this.initializeView(adminId, id);
            } catch (SQLException ex) {
                Logger.getLogger(AdminDetailsView.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setLocation((int) ((DesktopPane.getSize().width - this.getSize().width) / 2), (int) ((DesktopPane.getSize().height - this.getSize().height) / 2));
            this.setVisible(true);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    void initializeView(int adminId, int id) throws SQLException {
        this.adminId = adminId;
        this.id = id;
        display(id);
    }

    public void display(int id) throws SQLException {
        List<Admins> admin = AdminsSQL.getAdminsDetailsById(id);
        admin.forEach((Admins admins) -> {
            String title1 = admins.getTitle();
            String name = admins.getName();
            String role = admins.getRole();
            String nic = admins.getNic();
            String phone = admins.getPhone();
            String email = admins.getEmail();
            lblTitle.setText(title1);
            lblName.setText(name);
            lblRole.setText(role);
            lblNic.setText(nic);
            lblPhone.setText(phone);
            lblMail.setText(email);

        });
    }

    private void pfAction() throws SQLException {
        JPasswordField jpf = new JPasswordField();
        int action = JOptionPane.showConfirmDialog(this, jpf, "Enter your Password", JOptionPane.OK_CANCEL_OPTION);
        if (action == 0) {
            if (AdminsSQL.getPassword(adminId).equals(new String(jpf.getPassword()))) {
                if (lblRole.getText().equals("Admin")) {
                    AdminsSQL.setRole(id, "Head");
                } else {
                    AdminsSQL.setRole(id, "Admin");
                }
                JOptionPane.showMessageDialog(this, "Successfully Updated!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect Password");
                pfAction();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMail1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblNic;
    private javax.swing.JLabel lblNic1;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRole1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}
