/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rad.demo.ui.replacements;

import com.rad.demo.database.ApparatusSQL;
import com.rad.demo.database.ListSQL;
import com.rad.demo.entities.Apparatus;
import com.rad.demo.entities.Replacements;
import com.rad.demo.ui.DashBoardView;
import static com.rad.demo.ui.DashBoardView.DesktopPane;
import com.rad.demo.ui.lists.ListItemsView;
import java.awt.Component;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BHARATHA
 */
public class ReplacementsView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReplacementsView
     */
    public ReplacementsView() {
        initComponents();
    }

    private DefaultTableModel dtmList;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 120, 212)));
        setClosable(true);
        setTitle("Replacements");

        tblList.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "List ID", "Group", "Family", "Component", "Qty."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblList);
        if (tblList.getColumnModel().getColumnCount() > 0) {
            tblList.getColumnModel().getColumn(0).setMinWidth(0);
            tblList.getColumnModel().getColumn(0).setPreferredWidth(60);
            tblList.getColumnModel().getColumn(0).setMaxWidth(60);
            tblList.getColumnModel().getColumn(1).setMinWidth(0);
            tblList.getColumnModel().getColumn(1).setPreferredWidth(90);
            tblList.getColumnModel().getColumn(1).setMaxWidth(90);
            tblList.getColumnModel().getColumn(2).setMinWidth(0);
            tblList.getColumnModel().getColumn(2).setPreferredWidth(175);
            tblList.getColumnModel().getColumn(2).setMaxWidth(175);
            tblList.getColumnModel().getColumn(4).setMinWidth(0);
            tblList.getColumnModel().getColumn(4).setPreferredWidth(60);
            tblList.getColumnModel().getColumn(4).setMaxWidth(60);
        }

        jButton1.setText("Replace");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int count = tblList.getSelectedRowCount();
        switch (count) {
            case 0:
                JOptionPane.showMessageDialog(this, "Select the component you want to mark as completed", "", JOptionPane.INFORMATION_MESSAGE);
                break;
            case 1:
                int input = JOptionPane.showConfirmDialog(this, "Do you want to mark this item as completed?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (input == JOptionPane.YES_OPTION) {
                    try {
                        int row = tblList.getSelectedRow();
                        if (row >= 0) {

                            String component = tblList.getValueAt(row, 3).toString();
                            Apparatus temp = ApparatusSQL.getComponentDetails(component);
                            int lId = Integer.parseInt(tblList.getValueAt(row, 0).toString());
                            int cID = temp.getId();
                            int qtyStock = temp.getQty();
                            int qtyList = Integer.parseInt(tblList.getValueAt(row, 4).toString());
                            int newQty = qtyStock + qtyList;
                            ListSQL.setQty(cID, newQty);
                            ListSQL.replaceBrokenComponent(lId, cID);
                            JOptionPane.showMessageDialog(this, "The component was replaced", "", JOptionPane.INFORMATION_MESSAGE);
                            this.dispose();
                            tblList.removeAll();
                            DashBoardView.DesktopPane.remove((Component) this);
                            DashBoardView.DesktopPane.add((Component) this);
                            this.initializeView();
                            this.setLocation((int) ((DesktopPane.getSize().width - this.getSize().width) / 2), (int) ((DesktopPane.getSize().height - this.getSize().height) / 2));
                            this.setVisible(true);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(ListItemsView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                break;
            default:
                JOptionPane.showMessageDialog(this, "Select one component at a time", "", JOptionPane.INFORMATION_MESSAGE);
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblList;
    // End of variables declaration//GEN-END:variables

    public void initializeView() throws SQLException {
        setDtmList();
        List<Replacements> list = ListSQL.getAllReplacements();
        list.forEach((Replacements replacements) -> {
            try {
                int lId = replacements.getlId();
                int cId = replacements.getcId();
                int qty = replacements.getQty();

                Apparatus temp = ApparatusSQL.searchById(Integer.toString(cId));
                dtmList.addRow(new Object[]{lId, temp.getGroup(), temp.getFamily(), temp.getComponent(), qty});
            } catch (SQLException ex) {
                Logger.getLogger(ReplacementsView.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    private void setDtmList() {
        dtmList = (DefaultTableModel) this.tblList.getModel();
        dtmList.getDataVector().removeAllElements();
        dtmList.fireTableDataChanged();
    }
}
