/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rad.demo.ui;

import com.rad.demo.database.DashBoardSQL;
import com.rad.demo.entities.LogIn;
import com.rad.demo.ui.admins.AdminDetailsView;
import com.rad.demo.ui.admins.ChangePWView;
import com.rad.demo.ui.admins.ChangeUNameView;
import com.rad.demo.ui.admins.EditProfileView;
import com.rad.demo.ui.apparatus.ApparatusView;
import com.rad.demo.ui.apparatus.ManageApparatusView;
import com.rad.demo.ui.issue.StudentLogInView;
import com.rad.demo.ui.lists.ListsView;
import com.rad.demo.ui.replacements.ReplacementsView;
import com.rad.demo.ui.reports.ReportsView;
import com.rad.demo.ui.utils.ColorPalette;
import java.awt.Component;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author BHARATHA
 */
public class DashBoardView extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public static ArrayList<Object> indexes;
    private String uName; 
    private int adminId;
    private String title;

    private final LogInView logInView = new LogInView();
    private final ApparatusView apparatusView = new ApparatusView();
    private final StudentLogInView studentLogInView = new StudentLogInView();
    private final ListsView listsView = new ListsView();
    private final ReplacementsView replacementsView = new ReplacementsView();
    private final ManageApparatusView manageApparatusView = new ManageApparatusView();
    private final ReportsView reportsView = new ReportsView();
    private final EditProfileView editProfileView = new EditProfileView();
    private final ChangeUNameView changeUNameView = new ChangeUNameView();
    private final ChangePWView changePWView = new ChangePWView();
    private final AdminDetailsView adView = new AdminDetailsView();
    

    public DashBoardView() {
        initComponents();
        fullScreen();
        setWallpaper();
        //pnlIssueBtn.setVisible(false);
        //pnlNotReceivedBtn.setVisible(false);
        //pnlListBtn.setVisible(false);
        //pnlReplacementsBtn.setVisible(false);
        //pnlReportsBtn.setVisible(false);
        //pnlManageApparatusBtn.setVisible(false);
        //pnlAdminsBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpmProfile = new javax.swing.JPopupMenu();
        editProfile = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        changeUName = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        changePW = new javax.swing.JMenuItem();
        jPanelFrame = new javax.swing.JPanel();
        pnlTopBar = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        lblSystemName = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        pnlWindowControl = new javax.swing.JPanel();
        pnlMinimizeBtn = new javax.swing.JPanel();
        btnMinimize = new javax.swing.JLabel();
        pnlCloseBtn = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        pnlAccountDetails = new javax.swing.JPanel();
        pnlLogOutBtn = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JLabel();
        lblUName = new javax.swing.JLabel();
        pnlSideBar = new javax.swing.JPanel();
        pnlApparatusListBtn = new javax.swing.JPanel();
        btnApparatusList = new javax.swing.JLabel();
        pnlIssueBtn = new javax.swing.JPanel();
        btnIssue = new javax.swing.JLabel();
        pnlListsBtn = new javax.swing.JPanel();
        btnLists = new javax.swing.JLabel();
        pnlReplacementsBtn = new javax.swing.JPanel();
        btnReplacements = new javax.swing.JLabel();
        pnlReportsBtn = new javax.swing.JPanel();
        btnReports = new javax.swing.JLabel();
        pnlManageApparatusBtn = new javax.swing.JPanel();
        btnManageApparatus = new javax.swing.JLabel();
        pnlAdminsBtn = new javax.swing.JPanel();
        btnAdmins = new javax.swing.JLabel();
        DesktopPane = new javax.swing.JDesktopPane();
        lblBack = new javax.swing.JLabel();

        editProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rad/demo/icons/PopUpMenu/EditProfile icon.png"))); // NOI18N
        editProfile.setText("Edit Profile");
        editProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editProfileMouseReleased(evt);
            }
        });
        JpmProfile.add(editProfile);
        JpmProfile.add(jSeparator1);

        changeUName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rad/demo/icons/PopUpMenu/ChangeUName icon.png"))); // NOI18N
        changeUName.setText("Change User Name");
        changeUName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                changeUNameMouseReleased(evt);
            }
        });
        JpmProfile.add(changeUName);
        JpmProfile.add(jSeparator2);

        changePW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rad/demo/icons/PopUpMenu/ChangePW icon.png"))); // NOI18N
        changePW.setText("Change Password");
        changePW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                changePWMouseReleased(evt);
            }
        });
        JpmProfile.add(changePW);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelFrame.setLayout(new java.awt.BorderLayout());

        pnlTopBar.setBackground(new java.awt.Color(0, 0, 0));
        pnlTopBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 120, 212)));
        pnlTopBar.setLayout(new java.awt.GridLayout(1, 0));

        pnlLeft.setOpaque(false);

        lblSystemName.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblSystemName.setForeground(new java.awt.Color(255, 255, 255));
        lblSystemName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSystemName.setText("Apparatus Controlling System");

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSystemName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSystemName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );

        pnlTopBar.add(pnlLeft);

        pnlRight.setOpaque(false);

        pnlWindowControl.setOpaque(false);

        pnlMinimizeBtn.setBackground(new java.awt.Color(0, 0, 0));

        btnMinimize.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setText("-");
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMinimizelblCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlMinimizeBtnLayout = new javax.swing.GroupLayout(pnlMinimizeBtn);
        pnlMinimizeBtn.setLayout(pnlMinimizeBtnLayout);
        pnlMinimizeBtnLayout.setHorizontalGroup(
            pnlMinimizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        pnlMinimizeBtnLayout.setVerticalGroup(
            pnlMinimizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlCloseBtn.setBackground(new java.awt.Color(0, 0, 0));

        btnClose.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("X");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlCloseBtnLayout = new javax.swing.GroupLayout(pnlCloseBtn);
        pnlCloseBtn.setLayout(pnlCloseBtnLayout);
        pnlCloseBtnLayout.setHorizontalGroup(
            pnlCloseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        pnlCloseBtnLayout.setVerticalGroup(
            pnlCloseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlWindowControlLayout = new javax.swing.GroupLayout(pnlWindowControl);
        pnlWindowControl.setLayout(pnlWindowControlLayout);
        pnlWindowControlLayout.setHorizontalGroup(
            pnlWindowControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWindowControlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlMinimizeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCloseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlWindowControlLayout.setVerticalGroup(
            pnlWindowControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlMinimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlAccountDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlAccountDetails.setOpaque(false);

        pnlLogOutBtn.setBackground(new java.awt.Color(0, 0, 0));

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rad/demo/icons/DashBoard/LogOut-icon.png"))); // NOI18N
        btnLogOut.setToolTipText("Log out");
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogOutMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogOutMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlLogOutBtnLayout = new javax.swing.GroupLayout(pnlLogOutBtn);
        pnlLogOutBtn.setLayout(pnlLogOutBtnLayout);
        pnlLogOutBtnLayout.setHorizontalGroup(
            pnlLogOutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogOutBtnLayout.createSequentialGroup()
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        pnlLogOutBtnLayout.setVerticalGroup(
            pnlLogOutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        lblUName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUName.setForeground(new java.awt.Color(255, 255, 255));
        lblUName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rad/demo/icons/DashBoard/User-icon.png"))); // NOI18N
        lblUName.setIconTextGap(2);
        lblUName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblUNameMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlAccountDetailsLayout = new javax.swing.GroupLayout(pnlAccountDetails);
        pnlAccountDetails.setLayout(pnlAccountDetailsLayout);
        pnlAccountDetailsLayout.setHorizontalGroup(
            pnlAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccountDetailsLayout.createSequentialGroup()
                .addComponent(lblUName, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlAccountDetailsLayout.setVerticalGroup(
            pnlAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblUName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGap(0, 187, Short.MAX_VALUE)
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlWindowControl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAccountDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addComponent(pnlWindowControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(pnlAccountDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pnlTopBar.add(pnlRight);

        jPanelFrame.add(pnlTopBar, java.awt.BorderLayout.PAGE_START);

        pnlSideBar.setBackground(new java.awt.Color(31, 31, 31));
        pnlSideBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 120, 212)));
        pnlSideBar.setPreferredSize(new java.awt.Dimension(220, 463));
        pnlSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlApparatusListBtn.setBackground(new java.awt.Color(31, 31, 31));

        btnApparatusList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnApparatusList.setForeground(new java.awt.Color(255, 255, 255));
        btnApparatusList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rad/demo/icons/DashBoard/ApparatusList-icon.png"))); // NOI18N
        btnApparatusList.setText("  Apparatus List");
        btnApparatusList.setIconTextGap(0);
        btnApparatusList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnApparatusListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnApparatusListMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnApparatusListMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlApparatusListBtnLayout = new javax.swing.GroupLayout(pnlApparatusListBtn);
        pnlApparatusListBtn.setLayout(pnlApparatusListBtnLayout);
        pnlApparatusListBtnLayout.setHorizontalGroup(
            pnlApparatusListBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnApparatusList, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pnlApparatusListBtnLayout.setVerticalGroup(
            pnlApparatusListBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlApparatusListBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnApparatusList, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlSideBar.add(pnlApparatusListBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 40));

        pnlIssueBtn.setBackground(new java.awt.Color(31, 31, 31));

        btnIssue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIssue.setForeground(new java.awt.Color(255, 255, 255));
        btnIssue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rad/demo/icons/DashBoard/Issue-icon.png"))); // NOI18N
        btnIssue.setText("  Issue");
        btnIssue.setIconTextGap(0);
        btnIssue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIssueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIssueMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnIssueMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlIssueBtnLayout = new javax.swing.GroupLayout(pnlIssueBtn);
        pnlIssueBtn.setLayout(pnlIssueBtnLayout);
        pnlIssueBtnLayout.setHorizontalGroup(
            pnlIssueBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIssue, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pnlIssueBtnLayout.setVerticalGroup(
            pnlIssueBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlSideBar.add(pnlIssueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 200, 40));

        pnlListsBtn.setBackground(new java.awt.Color(31, 31, 31));

        btnLists.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLists.setForeground(new java.awt.Color(255, 255, 255));
        btnLists.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rad/demo/icons/DashBoard/Lists-icon.png"))); // NOI18N
        btnLists.setText("  Lists");
        btnLists.setIconTextGap(0);
        btnLists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListsMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnListsMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlListsBtnLayout = new javax.swing.GroupLayout(pnlListsBtn);
        pnlListsBtn.setLayout(pnlListsBtnLayout);
        pnlListsBtnLayout.setHorizontalGroup(
            pnlListsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLists, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pnlListsBtnLayout.setVerticalGroup(
            pnlListsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListsBtnLayout.createSequentialGroup()
                .addComponent(btnLists, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlSideBar.add(pnlListsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 40));

        pnlReplacementsBtn.setBackground(new java.awt.Color(31, 31, 31));

        btnReplacements.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReplacements.setForeground(new java.awt.Color(255, 255, 255));
        btnReplacements.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rad/demo/icons/DashBoard/Replacements-icon.png"))); // NOI18N
        btnReplacements.setText("  Replacements");
        btnReplacements.setIconTextGap(0);
        btnReplacements.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReplacementsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReplacementsMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnReplacementsMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlReplacementsBtnLayout = new javax.swing.GroupLayout(pnlReplacementsBtn);
        pnlReplacementsBtn.setLayout(pnlReplacementsBtnLayout);
        pnlReplacementsBtnLayout.setHorizontalGroup(
            pnlReplacementsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReplacements, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pnlReplacementsBtnLayout.setVerticalGroup(
            pnlReplacementsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReplacements, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSideBar.add(pnlReplacementsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 200, 40));

        pnlReportsBtn.setBackground(new java.awt.Color(31, 31, 31));

        btnReports.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rad/demo/icons/DashBoard/Reports-icon.png"))); // NOI18N
        btnReports.setText("  Reports");
        btnReports.setIconTextGap(0);
        btnReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportsMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnReportsMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlReportsBtnLayout = new javax.swing.GroupLayout(pnlReportsBtn);
        pnlReportsBtn.setLayout(pnlReportsBtnLayout);
        pnlReportsBtnLayout.setHorizontalGroup(
            pnlReportsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReports, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pnlReportsBtnLayout.setVerticalGroup(
            pnlReportsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSideBar.add(pnlReportsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 200, 40));

        pnlManageApparatusBtn.setBackground(new java.awt.Color(31, 31, 31));

        btnManageApparatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnManageApparatus.setForeground(new java.awt.Color(255, 255, 255));
        btnManageApparatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rad/demo/icons/DashBoard/ManageApparatus-icon.png"))); // NOI18N
        btnManageApparatus.setText("  Manage Apparatus");
        btnManageApparatus.setIconTextGap(0);
        btnManageApparatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageApparatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageApparatusMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnManageApparatusMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlManageApparatusBtnLayout = new javax.swing.GroupLayout(pnlManageApparatusBtn);
        pnlManageApparatusBtn.setLayout(pnlManageApparatusBtnLayout);
        pnlManageApparatusBtnLayout.setHorizontalGroup(
            pnlManageApparatusBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnManageApparatus, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pnlManageApparatusBtnLayout.setVerticalGroup(
            pnlManageApparatusBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnManageApparatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSideBar.add(pnlManageApparatusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 40));

        pnlAdminsBtn.setBackground(new java.awt.Color(31, 31, 31));

        btnAdmins.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdmins.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rad/demo/icons/DashBoard/Admins-icon.png"))); // NOI18N
        btnAdmins.setText("  Admins");
        btnAdmins.setIconTextGap(0);
        btnAdmins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdminsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminsMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAdminsMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminsBtnLayout = new javax.swing.GroupLayout(pnlAdminsBtn);
        pnlAdminsBtn.setLayout(pnlAdminsBtnLayout);
        pnlAdminsBtnLayout.setHorizontalGroup(
            pnlAdminsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAdmins, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pnlAdminsBtnLayout.setVerticalGroup(
            pnlAdminsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAdmins, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSideBar.add(pnlAdminsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, 40));

        jPanelFrame.add(pnlSideBar, java.awt.BorderLayout.LINE_START);

        DesktopPane.setBackground(new java.awt.Color(153, 153, 153));
        DesktopPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 120, 212)));
        DesktopPane.setOpaque(false);

        DesktopPane.setLayer(lblBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBack, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        jPanelFrame.add(DesktopPane, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApparatusListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApparatusListMouseReleased
        try {
            apparatusView.dispose();
            DashBoardView.DesktopPane.remove((Component) apparatusView);
            DashBoardView.DesktopPane.add((Component) apparatusView);
            apparatusView.initializeView();
            apparatusView.setLocation((int) ((DesktopPane.getSize().width - apparatusView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - apparatusView.getSize().height) / 2));
            apparatusView.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoardView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnApparatusListMouseReleased

    private void btnCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseReleased
        int input = JOptionPane.showConfirmDialog(this, "Do you want to exit from the system without logging out?", "", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (input == JOptionPane.YES_OPTION) {
            System.gc();
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseMouseReleased

    private void btnLogOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseReleased
        int input = JOptionPane.showConfirmDialog(this, "Do you want to Log Out from the system?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (input == JOptionPane.YES_OPTION) {
            DashBoardSQL.setLoggedIn(uName);
            System.gc();
            this.dispose();
            logInView.initializeView();
            logInView.setVisible(true);
        }
    }//GEN-LAST:event_btnLogOutMouseReleased

    private void btnMinimizelblCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizelblCloseMouseReleased
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizelblCloseMouseReleased

    private void btnIssueMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssueMouseReleased
        studentLogInView.dispose();
        DashBoardView.DesktopPane.remove((Component) studentLogInView);
        DashBoardView.DesktopPane.add((Component) studentLogInView);
        studentLogInView.initializeView();
        studentLogInView.setAdminId(adminId);
        studentLogInView.setLocation((int) ((DesktopPane.getSize().width - studentLogInView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - studentLogInView.getSize().height) / 2));
        studentLogInView.setVisible(true);
    }//GEN-LAST:event_btnIssueMouseReleased

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        pnlMinimizeBtn.setBackground(ColorPalette.BG_BTN_SELECTED);
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        pnlMinimizeBtn.setBackground(ColorPalette.BG_BLACK);
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        pnlCloseBtn.setBackground(ColorPalette.BG_CLOSE1);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        pnlCloseBtn.setBackground(ColorPalette.BG_BLACK);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseEntered
        btnLogOut.setBorder(BorderFactory.createLineBorder(ColorPalette.BORDERLINE, 2));
    }//GEN-LAST:event_btnLogOutMouseEntered

    private void btnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseExited
        btnLogOut.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_btnLogOutMouseExited

    private void btnApparatusListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApparatusListMouseEntered
        pnlApparatusListBtn.setBackground(ColorPalette.PANEL_BTN_BG_1);
    }//GEN-LAST:event_btnApparatusListMouseEntered

    private void btnApparatusListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApparatusListMouseExited
        pnlApparatusListBtn.setBackground(ColorPalette.PANEL_BTN_BG_0);
    }//GEN-LAST:event_btnApparatusListMouseExited

    private void btnIssueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssueMouseEntered
        pnlIssueBtn.setBackground(ColorPalette.PANEL_BTN_BG_1);
    }//GEN-LAST:event_btnIssueMouseEntered

    private void btnListsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListsMouseEntered
        pnlListsBtn.setBackground(ColorPalette.PANEL_BTN_BG_1);
    }//GEN-LAST:event_btnListsMouseEntered

    private void btnReplacementsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReplacementsMouseEntered
        pnlReplacementsBtn.setBackground(ColorPalette.PANEL_BTN_BG_1);
    }//GEN-LAST:event_btnReplacementsMouseEntered

    private void btnReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseEntered
        pnlReportsBtn.setBackground(ColorPalette.PANEL_BTN_BG_1);
    }//GEN-LAST:event_btnReportsMouseEntered

    private void btnManageApparatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageApparatusMouseEntered
        pnlManageApparatusBtn.setBackground(ColorPalette.PANEL_BTN_BG_1);
    }//GEN-LAST:event_btnManageApparatusMouseEntered

    private void btnAdminsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminsMouseEntered
        pnlAdminsBtn.setBackground(ColorPalette.PANEL_BTN_BG_1);
    }//GEN-LAST:event_btnAdminsMouseEntered

    private void btnIssueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssueMouseExited
        pnlIssueBtn.setBackground(ColorPalette.PANEL_BTN_BG_0);
    }//GEN-LAST:event_btnIssueMouseExited

    private void btnListsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListsMouseExited
        pnlListsBtn.setBackground(ColorPalette.PANEL_BTN_BG_0);
    }//GEN-LAST:event_btnListsMouseExited

    private void btnReplacementsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReplacementsMouseExited
        pnlReplacementsBtn.setBackground(ColorPalette.PANEL_BTN_BG_0);
    }//GEN-LAST:event_btnReplacementsMouseExited

    private void btnReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseExited
        pnlReportsBtn.setBackground(ColorPalette.PANEL_BTN_BG_0);
    }//GEN-LAST:event_btnReportsMouseExited

    private void btnManageApparatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageApparatusMouseExited
        pnlManageApparatusBtn.setBackground(ColorPalette.PANEL_BTN_BG_0);
    }//GEN-LAST:event_btnManageApparatusMouseExited

    private void btnAdminsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminsMouseExited
        pnlAdminsBtn.setBackground(ColorPalette.PANEL_BTN_BG_0);
    }//GEN-LAST:event_btnAdminsMouseExited

    private void btnListsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListsMouseReleased
        try {
            listsView.dispose();
            DashBoardView.DesktopPane.remove((Component) listsView);
            DashBoardView.DesktopPane.add((Component) listsView);
            listsView.initializeView();
            listsView.setAdminId(adminId);
            listsView.setLocation((int) ((DesktopPane.getSize().width - listsView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - listsView.getSize().height) / 2));
            listsView.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoardView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListsMouseReleased

    private void btnReplacementsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReplacementsMouseReleased
        try {
            replacementsView.dispose();
            DashBoardView.DesktopPane.remove((Component) replacementsView);
            DashBoardView.DesktopPane.add((Component) replacementsView);
            replacementsView.initializeView();
            replacementsView.setLocation((int) ((DesktopPane.getSize().width - replacementsView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - replacementsView.getSize().height) / 2));
            replacementsView.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoardView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReplacementsMouseReleased

    private void btnManageApparatusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageApparatusMouseReleased
        manageApparatusView.dispose();
        DashBoardView.DesktopPane.remove((Component) manageApparatusView);
        DashBoardView.DesktopPane.add((Component) manageApparatusView);
        manageApparatusView.initializeView();
        manageApparatusView.setAdminId(adminId);
        manageApparatusView.setLocation((int) ((DesktopPane.getSize().width - manageApparatusView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - manageApparatusView.getSize().height) / 2));
        manageApparatusView.setVisible(true);
    }//GEN-LAST:event_btnManageApparatusMouseReleased

    private void btnReportsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseReleased
        reportsView.dispose();
        DashBoardView.DesktopPane.remove((Component) reportsView);
        DashBoardView.DesktopPane.add((Component) reportsView);
        reportsView.initializeView(title);
        reportsView.setLocation((int) ((DesktopPane.getSize().width - reportsView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - reportsView.getSize().height) / 2));
        reportsView.setVisible(true);
    }//GEN-LAST:event_btnReportsMouseReleased

    private void lblUNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUNameMouseReleased
        if (evt.getButton() == 3) {

            Point p1 = getMousePosition();
            Point p = lblUName.getLocationOnScreen();
            JpmProfile.show(this, (int) p.getX() + 82, (int) p.getY() + lblUName.getHeight());
        }
    }//GEN-LAST:event_lblUNameMouseReleased

    private void editProfileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseReleased
        editProfileView.dispose();
        DashBoardView.DesktopPane.remove((Component) editProfileView);
        DashBoardView.DesktopPane.add((Component) editProfileView);
        try {
            editProfileView.initializeView(adminId);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoardView.class.getName()).log(Level.SEVERE, null, ex);
        }
        editProfileView.setLocation((int) ((DesktopPane.getSize().width - editProfileView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - editProfileView.getSize().height) / 2));
        editProfileView.setVisible(true);
    }//GEN-LAST:event_editProfileMouseReleased

    private void changeUNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeUNameMouseReleased
        changeUNameView.dispose();
        DashBoardView.DesktopPane.remove((Component) changeUNameView);
        DashBoardView.DesktopPane.add((Component) changeUNameView);
        changeUNameView.initializeView(adminId);
        changeUNameView.setLocation((int) ((DesktopPane.getSize().width - changeUNameView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - changeUNameView.getSize().height) / 2));
        changeUNameView.setVisible(true);
    }//GEN-LAST:event_changeUNameMouseReleased

    private void changePWMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePWMouseReleased
        changePWView.dispose();
        DashBoardView.DesktopPane.remove((Component) changePWView);
        DashBoardView.DesktopPane.add((Component) changePWView);
        changePWView.initializeView(adminId);
        changePWView.setLocation((int) ((DesktopPane.getSize().width - changePWView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - changePWView.getSize().height) / 2));
        changePWView.setVisible(true);
    }//GEN-LAST:event_changePWMouseReleased

    private void btnAdminsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminsMouseReleased
        adView.dispose();
        DashBoardView.DesktopPane.remove((Component) adView);
        DashBoardView.DesktopPane.add((Component) adView);
        try {
            adView.initializeView(adminId);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoardView.class.getName()).log(Level.SEVERE, null, ex);
        }
        adView.setLocation((int) ((DesktopPane.getSize().width - adView.getSize().width) / 2), (int) ((DesktopPane.getSize().height - adView.getSize().height) / 2));
        adView.setVisible(true);
    }//GEN-LAST:event_btnAdminsMouseReleased

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashBoardView().setVisible(true);
//            }
//        });
//    }
    private void fullScreen() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setMaximizedBounds(env.getMaximumWindowBounds());
    }

    private void setWallpaper() {
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/rad/demo/icons/Image.jpg"));
//        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
//        int width = ((int) size.getWidth())-190;
//        int height = ((int) size.getHeight())-128;

        int width = ((int) GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().width) - 222;
        int height = ((int) GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().height) - 133;
        DesktopPane.setSize(width, height);
        lblBack.setIcon(new ImageIcon(icon.getImage().getScaledInstance(DesktopPane.getSize().width, DesktopPane.getSize().height, Image.SCALE_SMOOTH)));
    }

    private void setUName(String title, String name) {
        lblUName.setText(title + " " + name);
    }

    private void setAdminVisible(boolean b) {
        pnlAdminsBtn.setVisible(b);
    }

    private void setUser(String uName) {
        this.uName = uName;
    }

    private void setAdminId(int adminId) {
        this.adminId = adminId;
    }

    public void initializeView(LogIn login) {
        this.setAdminTitle(login.getRole());
        if (title.equals("Head")) {
            this.setAdminVisible(true);
        } else {
            this.setAdminVisible(false);
        }
        this.setUser(login.getuName());
        this.setAdminId(login.getAdminId());
        this.setUName(login.getTitle(), login.getName());
        indexes = new ArrayList<>();
    }

    public void setAdminTitle(String title) {
        this.title = title;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JPopupMenu JpmProfile;
    private javax.swing.JLabel btnAdmins;
    private javax.swing.JLabel btnApparatusList;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnIssue;
    private javax.swing.JLabel btnLists;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JLabel btnManageApparatus;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel btnReplacements;
    private javax.swing.JLabel btnReports;
    private javax.swing.JMenuItem changePW;
    private javax.swing.JMenuItem changeUName;
    private javax.swing.JMenuItem editProfile;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblSystemName;
    private javax.swing.JLabel lblUName;
    private javax.swing.JPanel pnlAccountDetails;
    private javax.swing.JPanel pnlAdminsBtn;
    private javax.swing.JPanel pnlApparatusListBtn;
    private javax.swing.JPanel pnlCloseBtn;
    private javax.swing.JPanel pnlIssueBtn;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlListsBtn;
    private javax.swing.JPanel pnlLogOutBtn;
    private javax.swing.JPanel pnlManageApparatusBtn;
    private javax.swing.JPanel pnlMinimizeBtn;
    private javax.swing.JPanel pnlReplacementsBtn;
    private javax.swing.JPanel pnlReportsBtn;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlSideBar;
    private javax.swing.JPanel pnlTopBar;
    private javax.swing.JPanel pnlWindowControl;
    // End of variables declaration//GEN-END:variables
}
