/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rad.demo.ui;

import com.rad.demo.database.AdminsSQL;
import com.rad.demo.database.LogInSQL;
import com.rad.demo.entities.LogIn;
import com.rad.demo.ui.utils.ColorPalette;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author BHARATHA
 */
public class LogInView extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogInView() {
        initComponents();
        setWallpaper();
        setPosition();
        initializeView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFrame = new javax.swing.JPanel();
        pnlLogIn = new javax.swing.JPanel();
        pnlErrorMsg = new javax.swing.JPanel();
        lblErrorMsg = new javax.swing.JLabel();
        pnlLogIn1 = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        pnlLogInBtn = new javax.swing.JPanel();
        btnLogIn = new javax.swing.JLabel();
        pnlTitleBar = new javax.swing.JPanel();
        pnlCloseBtn = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        PanelFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        PanelFrame.setOpaque(false);
        PanelFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogIn.setBackground(new java.awt.Color(36, 36, 36));

        pnlErrorMsg.setOpaque(false);

        lblErrorMsg.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblErrorMsg.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlErrorMsgLayout = new javax.swing.GroupLayout(pnlErrorMsg);
        pnlErrorMsg.setLayout(pnlErrorMsgLayout);
        pnlErrorMsgLayout.setHorizontalGroup(
            pnlErrorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlErrorMsgLayout.createSequentialGroup()
                .addComponent(lblErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlErrorMsgLayout.setVerticalGroup(
            pnlErrorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        pnlLogIn1.setOpaque(false);
        pnlLogIn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("User Name :");
        pnlLogIn1.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        txtUserName.setBackground(new java.awt.Color(66, 66, 66));
        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 120, 212)));
        txtUserName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtUserNameMouseReleased(evt);
            }
        });
        pnlLogIn1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 150, -1));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password   :");
        pnlLogIn1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtPassword.setBackground(new java.awt.Color(66, 66, 66));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 120, 212)));
        txtPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtPasswordMouseReleased(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        pnlLogIn1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 150, -1));

        pnlLogInBtn.setBackground(new java.awt.Color(0, 108, 190));

        btnLogIn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogIn.setText("Log In");
        btnLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogInMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogInMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlLogInBtnLayout = new javax.swing.GroupLayout(pnlLogInBtn);
        pnlLogInBtn.setLayout(pnlLogInBtnLayout);
        pnlLogInBtnLayout.setHorizontalGroup(
            pnlLogInBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        pnlLogInBtnLayout.setVerticalGroup(
            pnlLogInBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        pnlLogIn1.add(pnlLogInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        javax.swing.GroupLayout pnlLogInLayout = new javax.swing.GroupLayout(pnlLogIn);
        pnlLogIn.setLayout(pnlLogInLayout);
        pnlLogInLayout.setHorizontalGroup(
            pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogInLayout.createSequentialGroup()
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlLogIn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlErrorMsg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLogInLayout.setVerticalGroup(
            pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogInLayout.createSequentialGroup()
                .addComponent(pnlErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLogIn1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelFrame.add(pnlLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 300, 180));

        pnlTitleBar.setBackground(new java.awt.Color(0, 0, 0));

        pnlCloseBtn.setBackground(new java.awt.Color(0, 0, 0));
        pnlCloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCloseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCloseBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlCloseBtnMousePressed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("X");

        javax.swing.GroupLayout pnlCloseBtnLayout = new javax.swing.GroupLayout(pnlCloseBtn);
        pnlCloseBtn.setLayout(pnlCloseBtnLayout);
        pnlCloseBtnLayout.setHorizontalGroup(
            pnlCloseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCloseBtnLayout.createSequentialGroup()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlCloseBtnLayout.setVerticalGroup(
            pnlCloseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCloseBtnLayout.createSequentialGroup()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTitleBarLayout = new javax.swing.GroupLayout(pnlTitleBar);
        pnlTitleBar.setLayout(pnlTitleBarLayout);
        pnlTitleBarLayout.setHorizontalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleBarLayout.createSequentialGroup()
                .addGap(0, 660, Short.MAX_VALUE)
                .addComponent(pnlCloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTitleBarLayout.setVerticalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlCloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelFrame.add(pnlTitleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 30));
        PanelFrame.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 720, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogInMouseReleased
        try {
            logInAction();
        } catch (SQLException ex) {
            Logger.getLogger(LogInView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogInMouseReleased

    private void pnlCloseBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCloseBtnMousePressed
        int input = JOptionPane.showConfirmDialog(this, "Do you want to exit from the system?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (input == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_pnlCloseBtnMousePressed

    private void txtUserNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseReleased
        lblErrorMsg.setText("");
    }//GEN-LAST:event_txtUserNameMouseReleased

    private void txtPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseReleased
        lblErrorMsg.setText("");
    }//GEN-LAST:event_txtPasswordMouseReleased

    private void pnlCloseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCloseBtnMouseEntered
        pnlCloseBtn.setBackground(ColorPalette.BG_CLOSE1);
    }//GEN-LAST:event_pnlCloseBtnMouseEntered

    private void pnlCloseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCloseBtnMouseExited
        pnlCloseBtn.setBackground(ColorPalette.BG_BLACK);
    }//GEN-LAST:event_pnlCloseBtnMouseExited

    private void btnLogInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogInMouseEntered
        pnlLogInBtn.setBackground(ColorPalette.LOGIN_BTN_BG_1);
    }//GEN-LAST:event_btnLogInMouseEntered

    private void btnLogInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogInMouseExited
        pnlLogInBtn.setBackground(ColorPalette.LOGIN_BTN_BG_0);
    }//GEN-LAST:event_btnLogInMouseExited

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                logInAction();
            } catch (SQLException ex) {
                Logger.getLogger(LogInView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtPasswordKeyReleased

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LogInView().setVisible(true);
//            }
//        });
//    }

    private void logInAction() throws SQLException{
        DashBoardView dbv = new DashBoardView();
        String uname = txtUserName.getText().toLowerCase().trim();
        String password = txtPassword.getText();
        if (uname.equals("")) {
            lblErrorMsg.setText("Enter User Name");
        } else if (password.equals("")) {
            lblErrorMsg.setText("Enter password");
        } else {
            LogIn login = LogInSQL.getLogIn(uname, password);
            
            if (login == null) {
                lblErrorMsg.setText("Invalid User Name or Password!");
                txtUserName.setText("");
                txtPassword.setText("");
            } else {
                int avl=AdminsSQL.getAvailableByuname(uname);
                if(avl==1){
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                Date date = new Date();
                LogInSQL.setLastLoggedIn(uname, sdf.format(date));
                dbv.initializeView(login);
                this.dispose();
                dbv.setVisible(true);
                }
                else{
                    lblErrorMsg.setText("Invalid User Name or Password!");
                }
            }
        }
    }
    
    public void initializeView(){
        txtUserName.setText("");
        txtPassword.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFrame;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnLogIn;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblErrorMsg;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnlCloseBtn;
    private javax.swing.JPanel pnlErrorMsg;
    private javax.swing.JPanel pnlLogIn;
    private javax.swing.JPanel pnlLogIn1;
    private javax.swing.JPanel pnlLogInBtn;
    private javax.swing.JPanel pnlTitleBar;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void setPosition() {
        setLocationRelativeTo(null);
    }

    private void setWallpaper() {
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/rad/demo/icons/Image.jpg"));
        lblBackground.setIcon(new ImageIcon(icon.getImage().getScaledInstance(720, 420, Image.SCALE_SMOOTH)));
    }
}
